import React from 'react';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/context/cartProvider";
import Wsp from '@/components/wsp'
import Navbar from '@/components/navbar'



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
      <CartProvider>
        <Navbar />
        {children}
        <Wsp />
      </CartProvider>
     
        </body>
    </html>
  );
}

